#!/usr/bin/env python3
"""
build.py — Subject Notes build script

Reads data/books.yaml   → writes books.json
Reads data/clusters.yaml → writes data/resource-gaps.md  (auto-updated every build)

Usage:
    python build.py

Requirements:
    pip install pyyaml
"""

import json
import sys
from pathlib import Path
from datetime import date

try:
    import yaml
except ImportError:
    print("Error: PyYAML not installed. Run: pip install pyyaml")
    sys.exit(1)

ROOT          = Path(__file__).parent
DATA_FILE     = ROOT / "data" / "books.yaml"
CLUSTERS_FILE = ROOT / "data" / "clusters.yaml"
OUTPUT_FILE   = ROOT / "books.json"
GAPS_FILE     = ROOT / "data" / "resource-gaps.md"

SECTION_ORDER = [
    "Engineering",
    "Computer Science",
    "Machine Learning & AI",
    "Mathematics",
    "Physics",
    "Life Sciences",
    "Miscellaneous",
]


def build_books():
    print("Building books.json...")

    if not DATA_FILE.exists():
        print(f"Error: {DATA_FILE} not found")
        sys.exit(1)

    with open(DATA_FILE, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    books = data.get("books", [])

    errors = []
    valid_books = []
    required = ["id", "title", "authors", "clusters"]

    for book in books:
        missing = [k for k in required if k not in book]
        if missing:
            errors.append(f"{book.get('id', '?')}: missing fields: {missing}")
            continue
        valid_books.append(book)

    if errors:
        print(f"\n{len(errors)} error(s):")
        for e in errors:
            print(f"  ✗ {e}")
        print()

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(valid_books, f, ensure_ascii=False, indent=2)

    print(f"OK: Built {len(valid_books)} books -> books.json")
    if errors:
        print(f"  ({len(errors)} book(s) skipped due to errors)")

    return valid_books


def build_resource_gaps(valid_books):
    if not CLUSTERS_FILE.exists():
        print("  (data/clusters.yaml not found — skipping resource-gaps report)")
        return

    with open(CLUSTERS_FILE, "r", encoding="utf-8") as f:
        clusters_data = yaml.safe_load(f)

    clusters = clusters_data.get("clusters", [])

    # Build a mapping: cluster_id -> list of book ids that cover it
    coverage = {}  # cluster_id -> [book_id, ...]
    for book in valid_books:
        for cid in book.get("clusters", []):
            coverage.setdefault(cid, []).append(book["id"])

    # Separate covered vs. not covered
    missing = [c for c in clusters if c["id"] not in coverage]
    covered = [c for c in clusters if c["id"] in coverage]

    lines = [
        "# Resource Gaps — Auto-generated by build.py",
        "",
        f"_Last updated: {date.today().isoformat()}. Do not edit manually — regenerated on every `push.ps1` run._",
        "",
        f"**{len(clusters)} clusters total · {len(covered)} with references · {len(missing)} missing references**",
        "",
        "---",
        "",
        "## Clusters without textbook references",
        "",
        "_These clusters have no entries in `data/books.yaml`. Add books before writing lessons._",
        "",
    ]

    for section in SECTION_ORDER:
        section_missing = [c for c in missing if c.get("section") == section]
        if section_missing:
            lines.append(f"### {section}")
            for c in section_missing:
                status = f" _(active — needs books!)_" if c.get("status") == "active" else ""
                lines.append(f"- `{c['id']}` — **{c['name']}**{status}")
            lines.append("")

    lines += [
        "---",
        "",
        "## Clusters with references",
        "",
        "_For reference: clusters that already have at least one book in `data/books.yaml`._",
        "",
    ]

    for section in SECTION_ORDER:
        section_covered = [c for c in covered if c.get("section") == section]
        if section_covered:
            lines.append(f"### {section}")
            for c in section_covered:
                book_ids = ", ".join(f"`{b}`" for b in coverage[c["id"]])
                lines.append(f"- `{c['id']}` — {c['name']} ({book_ids})")
            lines.append("")

    with open(GAPS_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"OK: Resource gaps report -> data/resource-gaps.md  ({len(missing)} missing / {len(covered)} covered)")


def main():
    valid_books = build_books()
    build_resource_gaps(valid_books)


if __name__ == "__main__":
    main()
